---
- name: My first play
  hosts: nodes
  tasks:
    - name: Ping my hosts
      ansible.builtin.ping:

    - name: Print message
      ansible.builtin.debug:
        msg: Hello world

    - name: Execute test shell script
        ansible.builtin.shell:
          cmd: pwd

    - name: Execute test shell script
      ansible.builtin.shell: test-script.sh
